import { BlogPost, PostType } from './types';

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: '京都的秋日',
    excerpt: '在清水寺的红叶中迷失方向。',
    content: '京都的秋天是红色的。走在二年坂的石板路上，仿佛穿越回了百年前。空气中弥漫着抹茶的香气，远处传来寺庙的钟声。这里的一草一木都充满了禅意，让人不由自主地慢下脚步。',
    date: '2023-11-15',
    type: PostType.MAP,
    locationName: '日本, 京都',
    location: { lat: 35.0116, lng: 135.7681 },
    imageUrl: 'https://picsum.photos/seed/kyoto/800/600',
  },
  {
    id: '2',
    title: '冰岛的极光',
    excerpt: '在那片绿色的光幕下，感受宇宙的呼吸。',
    content: '站在冰原之上，抬头仰望，那舞动的绿色光带如同神明的裙摆。寒冷已经不再重要，此刻只有纯粹的敬畏。大自然的鬼斧神工在这里展现得淋漓尽致。',
    date: '2024-01-20',
    type: PostType.MAP,
    locationName: '冰岛, 雷克雅未克',
    location: { lat: 64.1466, lng: -21.9426 },
    imageUrl: 'https://picsum.photos/seed/iceland/800/600',
  },
  {
    id: '3',
    title: '巴黎的午后',
    excerpt: '塞纳河畔的咖啡与发呆。',
    content: '不需要特定的目的地，只是在左岸随便找一家咖啡馆坐下。看着行色匆匆的路人，或者是牵手漫步的情侣。巴黎的浪漫不在于铁塔，而在于这些琐碎而美好的日常。',
    date: '2023-09-10',
    type: PostType.MAP,
    locationName: '法国, 巴黎',
    location: { lat: 48.8566, lng: 2.3522 },
    imageUrl: 'https://picsum.photos/seed/paris/800/600',
  },
  {
    id: '4',
    title: '纽约街头',
    excerpt: '混凝土森林中的梦想与喧嚣。',
    content: '时代广场的霓虹灯永不熄灭。这里是世界的中心，也是无数梦想开始的地方。每个人都在奔跑，每个人都有故事。',
    date: '2023-05-12',
    type: PostType.MAP,
    locationName: '美国, 纽约',
    location: { lat: 40.7128, lng: -74.0060 },
    imageUrl: 'https://picsum.photos/seed/nyc/800/600',
  },
  {
    id: '5',
    title: '关于旅行的意义',
    excerpt: '我们为什么要出发？',
    content: '有时候我在想，旅行到底是为了看风景，还是为了逃避当下的生活？或者，只是为了在一个陌生的地方，重新认识自己。每一次出发，都是一次内心的洗礼。',
    date: '2024-02-14',
    type: PostType.THOUGHT,
    imageUrl: 'https://picsum.photos/seed/thought1/800/600',
  },
  {
    id: '6',
    title: '胶片摄影的魅力',
    excerpt: '在这个数码时代，等待显影的惊喜。',
    content: '按快门的瞬间是永恒的，但等待冲洗的过程才是最迷人的。你不知道那张照片是否对焦准确，不知道光影是否完美，但那份不确定性，正是胶片的灵魂所在。',
    date: '2024-03-01',
    type: PostType.THOUGHT,
    imageUrl: 'https://picsum.photos/seed/film/800/600',
  },
    {
    id: '7',
    title: '悉尼歌剧院',
    excerpt: '海风吹过贝壳般的建筑。',
    content: '白色的风帆在蓝色的海港上熠熠生辉。坐在台阶上，听着海鸥的叫声，看着渡轮来来往往。',
    date: '2022-12-05',
    type: PostType.MAP,
    locationName: '澳大利亚, 悉尼',
    location: { lat: -33.8568, lng: 151.2153 },
    imageUrl: 'https://picsum.photos/seed/sydney/800/600',
  },
];
