import React, { useState } from 'react';
import { BlogPost } from '../types';
import { generateLocationInsight } from '../services/geminiService';
import { X, MapPin, Sparkles, Loader2 } from 'lucide-react';

interface PostModalProps {
  post: BlogPost;
  onClose: () => void;
}

const PostModal: React.FC<PostModalProps> = ({ post, onClose }) => {
  const [aiInsight, setAiInsight] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleGenerateInsight = async () => {
    if (!post.locationName) return;
    setIsLoading(true);
    const insight = await generateLocationInsight(post.locationName, post.title, post.content);
    setAiInsight(insight);
    setIsLoading(false);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm transition-opacity">
      <div className="bg-white rounded-lg shadow-2xl w-full max-w-4xl max-h-[90vh] overflow-hidden flex flex-col md:flex-row relative animate-[fadeIn_0.3s_ease-out]">
        
        {/* Close Button */}
        <button 
          onClick={onClose}
          className="absolute top-4 right-4 z-10 p-2 bg-white/50 hover:bg-white rounded-full transition-colors"
        >
          <X className="w-6 h-6 text-stone-800" />
        </button>

        {/* Image Section */}
        <div className="w-full md:w-1/2 h-64 md:h-auto bg-stone-100 relative">
           <img 
            src={post.imageUrl} 
            alt={post.title} 
            className="w-full h-full object-cover"
           />
           {post.locationName && (
             <div className="absolute bottom-4 left-4 bg-black/50 text-white px-3 py-1 rounded-full text-sm flex items-center gap-1 backdrop-blur-md">
               <MapPin size={14} />
               {post.locationName}
             </div>
           )}
        </div>

        {/* Content Section */}
        <div className="w-full md:w-1/2 p-8 overflow-y-auto font-serif">
          <div className="mb-2 text-stone-500 text-sm tracking-widest uppercase">{post.date}</div>
          <h2 className="text-3xl font-bold text-stone-900 mb-6 leading-tight">{post.title}</h2>
          
          <div className="prose prose-stone prose-lg text-stone-600 mb-8 whitespace-pre-wrap">
            {post.content}
          </div>

          <hr className="border-stone-200 my-6" />

          {/* AI Section */}
          <div className="bg-stone-50 p-6 rounded-xl border border-stone-100">
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-sans text-stone-800 font-semibold flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-primary" />
                地点灵感
              </h3>
              {!aiInsight && !isLoading && (
                 <button 
                  onClick={handleGenerateInsight}
                  className="text-xs bg-stone-800 text-white px-3 py-1.5 rounded-full hover:bg-stone-700 transition-colors flex items-center gap-1"
                 >
                   ✨ AI 生成感悟
                 </button>
              )}
            </div>

            {isLoading && (
              <div className="flex items-center gap-2 text-stone-500 text-sm animate-pulse">
                <Loader2 className="w-4 h-4 animate-spin" />
                正在聆听地点的声音...
              </div>
            )}

            {aiInsight && (
              <div className="relative">
                 <p className="text-stone-700 italic leading-relaxed text-sm">
                   {aiInsight}
                 </p>
                 <div className="text-right mt-2 text-xs text-stone-400 font-sans">
                   —— Generated by Gemini
                 </div>
              </div>
            )}
            
            {!aiInsight && !isLoading && (
              <p className="text-stone-400 text-sm">点击上方按钮，让 AI 为这段旅程写下一段注脚。</p>
            )}
          </div>

        </div>
      </div>
    </div>
  );
};

export default PostModal;
